name: core
description: Core library for PhitNest.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logger: ^2.0.1
  basic_utils: ^5.5.4
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^9.0.0
  amazon_cognito_identity_dart_2: ^3.5.0
  equatable: ^2.0.5
  async: ^2.11.0
  synchronized: ^3.1.0
  http: ^1.0.0
  json_types: ^2.0.2
  flutter_bloc: ^8.1.3
  
dev_dependencies:
  test: ^1.24.5
  lints: ^2.1.1
  dart_analysis:
    path: ../../configs/dart-analysis
