name: validation
description: Validation Utils
version: 1.0.0+1
publish_to: 'none'
environment:
<<<<<<< HEAD
  sdk: ">=2.13.4 <3.0.0"
=======
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/ic_launcher-playstore.png'

flutter:
  uses-material-design: true
>>>>>>> ebc467ce (Time package)
