name: phitnest_mobile
description: A new Flutter project.
publish_to: "none"
version: 0.0.2+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  equatable: ^2.0.5
  flutter_svg: ^1.1.4
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.8.4
  flutter_launcher_icons: ^0.10.0
  # phitnest_core:
  #   git: https://github.com/PhitNest/phitnest-core.git
  phitnest_core:
    path: ../phitnest-core
  flutter_verification_code:
    git:
      url: https://github.com/avraham-mayer/flutter_verification_code.git
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
