name: phitnest
description: Phitnest App
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.0.1
  provider: ^6.0.2
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  http: ^0.13.3
  geolocator: ^8.2.0
  smooth_page_indicator: ^1.0.0+2
  firebase_messaging: ^11.2.15
  intl_phone_number_input: ^0.7.0+2
  the_apple_sign_in: ^1.1.1
  easy_localization: ^3.0.0
  device:
    path: ./packages/device
  validation:
    path: ./packages/validation
  progress_widgets:
    path: ./packages/progress_widgets
  get_it: ^7.2.0
  device_preview: ^1.0.0
dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  integration_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/ic_launcher-playstore.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/