name: phitnest_mobile
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.17.6 <=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  geolocator: ^9.0.1
  get_it: ^7.2.0
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.4
  flutter_launcher_icons: ^0.12.0
  meta: ^1.8.0
  jwt_decode: ^0.3.1
  socket_io_client: ^2.0.1
  email_validator: ^2.1.17
  flutter_bloc: ^8.1.1
  logger: ^1.1.0
  pin_code_fields: ^7.4.0
  dio: ^5.0.1
  provider: ^6.0.5
  async: ^2.9.0
  image_picker: ^0.8.6
  camera: ^0.10.2
  cross_file_image: ^1.0.0
  image_editor: ^1.3.0
  basic_utils: ^5.4.2
  device_preview: ^1.1.0
  image_cropper: ^3.0.1
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  rxdart: ^0.27.7
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
