name: phitnest_admin
description: PhitNest Admin Dashboard
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  phitnest_core:
    path: ../phitnest-core
  go_router: ^6.5.5
  flutter_riverpod: ^2.3.4
  google_fonts: ^4.0.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true