name: phitnest
description: A new Flutter application.
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  shared_preferences: ^2.0.6
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^3.1.13
  image_picker: ^0.8.2
  firebase_storage: ^10.0.1
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git
  provider: ^6.0.2
  url_launcher: ^6.0.2
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  uuid: ^3.0.4
  video_thumbnail: ^0.5.0
  path_provider: ^2.0.2
  photo_view: ^0.13.0
  video_player: ^2.1.12
  http: ^0.13.3
  geolocator: ^8.2.0
  latlong2: ^0.8.0
  smooth_page_indicator: ^1.0.0+2
  firebase_messaging: ^11.2.15
  firebase_messaging: ^11.2.13
  intl_phone_number_input: ^0.7.0+2
  flutter_native_image: ^0.0.6+1
  flutter_sound: ^9.2.10
  the_apple_sign_in: ^1.1.1
  permission_handler: ^9.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  easy_localization: ^3.0.0
  navigation:
    path: ./packages/navigation
  location:
    path: ./packages/location
  display:
    path: ./packages/display
dev_dependencies:
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/images/ic_launcher-playstore.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/