name: phitnest_mobile
description: PhitNest mobile app
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=2.17.6 <=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.12.0
  device_preview: ^1.1.0
  image_cropper: ^3.0.1
  phitnest_core:
    path: ../phitnest-core
  flutter_bloc: ^8.1.2
  async: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
