name: phitnest_core
description: Utilities for PhitNest
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <=3.3.9"

dependencies:
  logger: ^1.1.0
  basic_utils: ^5.4.2
  dio: ^5.0.1
  shared_preferences: ^2.0.18
  flutter_secure_storage: ^8.0.0
  sealed_unions: ^3.0.3+1
  amazon_cognito_identity_dart_2: ^3.3.0
  equatable: ^2.0.5
