name: phitnest_core
description: Utilities for PhitNest
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logger: ^1.3.0
  basic_utils: ^5.5.4
  dio: ^5.1.2
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0
  amazon_cognito_identity_dart_2: ^3.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  async: ^2.11.0
  synchronized: ^3.1.0
  http: ^1.0.0
  
dev_dependencies:
  lints: ^2.1.0


