name: phitnest_mobile
description: A new Flutter project.
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=2.17.6 <=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  geolocator: ^9.0.1
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.12.0
  email_validator: ^2.1.17
  logger: ^1.1.0
  device_preview: ^1.1.0
  amazon_cognito_identity_dart_2: ^3.2.0
  image_cropper: ^3.0.1
  phitnest_utils:
    path: packages/phitnest_utils
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
