AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

  PhitNest-API

#####  Globals for Lambda functions #####
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        Region: "us-east-1"

#####  Input Parameters #####
Parameters:
  Stage:
    Type: String
    Description: Parameter for getting the deployment stage
    Default: default

#####  Environment Variables #####
Mappings:
  StagesMap:
    prod:
      VariableName: Value

Resources:
  #####  Lambda Functions #####
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cmd/lambdas/hello-world/app.lambdaHandler
      CodeUri: src/
      Runtime: nodejs16.x
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello-world
            Method: GET

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL to print Hello, World!"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello-world/"
