AdminCognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: !Sub "PhitNest-${Stage}-Admin"
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: true
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: true
        RequireUppercase: true
    EmailConfiguration:
      EmailSendingAccount: DEVELOPER
      From: PhitNest <verify@phitnest.com>
      ReplyToEmailAddress: verify@phitnest.com
      SourceArn: arn:aws:ses:us-east-1:235601651768:identity/phitnest.com
    AutoVerifiedAttributes:
      - email
    UsernameAttributes:
      - email
    Schema:
      - AttributeDataType: String
        Name: email
        Required: true

AdminCognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref AdminCognitoUserPool
    EnableTokenRevocation: true
    ExplicitAuthFlows:
      - ALLOW_USER_SRP_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
      - ALLOW_CUSTOM_AUTH
      - ALLOW_USER_PASSWORD_AUTH
    ClientName: !Sub "PhitNest-${Stage}-Admin"
    GenerateSecret: false