PhitNestApi:
  Type: AWS::Serverless::Api
  Properties:
    StageName: !Ref Stage
    Name: !Sub "PhitNest-${Stage}-API"
    EndpointConfiguration:
      Type: EDGE
    Auth:
      Authorizers:
        UserCognitoAuthorizer:
          UserPoolArn: !GetAtt UserCognitoUserPool.Arn
        AdminCognitoAuthorizer:
          UserPoolArn: !GetAtt AdminCognitoUserPool.Arn

LambdaSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupName: !Sub "LambdaSecurityGroup-${Stage}"
    GroupDescription: Lambda Security Group
    VpcId: !Ref DGraphVPC