DGraphEC2:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-0a887e401f7654935
    InstanceType: t3.medium
    IamInstanceProfile: !Ref DGraphSSMAgentProfile
    SecurityGroupIds:
      - !Ref DGraphSecurityGroup
    SubnetId: !Ref DGraphPrivateSubnet
    UserData: !Base64 |
      #!/bin/bash
      $$install_dgraph
      $$dgraph_ec2_services
      $$commit_schema
    Tags:
      - Key: Name
        Value: !Sub "DGraph-${Stage}"

DGraphSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupName: !Sub "DGraphSecurityGroup-${Stage}"
    GroupDescription: DGraph Security Group
    VpcId: !Ref DGraphVPC
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        SourceSecurityGroupId: !Ref LambdaSecurityGroup
