DGraphSSMAgentProfile:
  Type: AWS::IAM::InstanceProfile
  Properties:
    InstanceProfileName: !Sub "dgraph-ssm-access-${Stage}"
    Path: !Sub "/dgraph-ec2/${Stage}/"
    Roles:
      - !Ref DGraphSSMAgentRole

DGraphSSMAgentRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
    Path: !Sub "/dgraph-ec2/${Stage}/"
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

DGraphSSMEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcId: !Ref DGraphVPC
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssm"
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SecurityGroupIds:
      - !Ref SSMEndpointSecurityGroup
    SubnetIds:
      - !Ref DGraphPrivateSubnet

DGraphEC2MessagesEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcId: !Ref DGraphVPC
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2messages"
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SecurityGroupIds:
      - !Ref SSMEndpointSecurityGroup
    SubnetIds:
      - !Ref DGraphPrivateSubnet

DGraphSSMMessagesEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcId: !Ref DGraphVPC
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.ssmmessages"
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SecurityGroupIds:
      - !Ref SSMEndpointSecurityGroup
    SubnetIds:
      - !Ref DGraphPrivateSubnet

DGraphS3Endpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcId: !Ref DGraphVPC
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.s3"

SSMEndpointSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupName: !Sub "SSMEndpointSecurityGroup-${Stage}"
    GroupDescription: SSM Endpoint Security Group
    VpcId: !Ref DGraphVPC
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 10.0.1.0/24