DGraphEC2:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-0a887e401f7654935
    InstanceType: t3.medium
    IamInstanceProfile: !Ref DGraphSSMAgentProfile
    SecurityGroupIds:
      - !Ref DGraphSecurityGroup
    SubnetId: !Ref DGraphPrivateSubnet
    UserData: !Base64 |
      #!/bin/bash
      $$install_dgraph
      $$dgraph_ec2_services
      $$commit_schema
    Tags:
      - Key: Name
        Value: !Sub "DGraph-${Stage}"

DGraphVPCEndpoint:
  Type: AWS::EC2::VPCEndpoint
  Properties:
    VpcId: !Ref DGraphVPC
    ServiceName: !Sub "com.amazonaws.${AWS::Region}.ec2"
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SecurityGroupIds:
      - !Ref DGraphSecurityGroup
    SubnetIds:
      - !Ref DGraphPrivateSubnet

DGraphSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupName: !Sub "DGraphSecurityGroup-${Stage}"
    GroupDescription: DGraph Security Group
    VpcId: !Ref DGraphVPC
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8000
        ToPort: 8000
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 9080
        ToPort: 9080
        CidrIp: 0.0.0.0/0