enum RegistrationStatus {
    Unconfirmed
    WaitingForProfilePicture
    Confirmed
}

type User {
    id: String! @id
    firstName: String!
    lastName: String!
    createdAt: Int64!
    registrationStatus: RegistrationStatus!
    gym: Gym!
}