name: progress_widgets
description: Widgets for loading and alerts
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  progress_dialog:
    git:
      url: https://github.com/mostafaAbdelazim/progress_dialog.git