name: mobile
description: PhitNest Mobile App
publish_to: "none"
version: 0.2.0+13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  flutter_launcher_icons: ^0.13.1
  core:
    path: ../../packages/dart-core
  flutter_bloc: ^8.1.3
  pin_code_fields: ^8.0.1
  image_cropper: ^5.0.0
  camera: ^0.10.5+2
  image_editor: ^1.3.0
  image_picker: ^0.8.9
  http: ^1.0.0
  simple_gradient_text: ^1.2.4
  async: ^2.11.0
  json_types: ^2.0.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf
        - asset: assets/fonts/Metropolis-Bold.otf

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
