name: CD

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_ACCESS_KEY_SECRET:
        required: true
      API_DEPLOY_KEY:
        required: true
    inputs:
      deployment_env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Checkout phitnest-api
        uses: actions/checkout@v3
        with:
          repository: PhitNest/phitnest-api
          path: phitnest-api
          ssh-key: ${{ secrets.API_DEPLOY_KEY }}

      - name: Install dependencies
        run: npm i && npm i -g aws-cdk

      - name: Install API dependencies
        run: cd phitnest-api && npm i

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Deploy
        run: DEPLOYMENT_ENV=${{ inputs.deployment_env }} cdk deploy --require-approval never