// Do not edit this file. It is automatically generated by CI/CD.
const kUserPoolId = 'us-east-1_fcJ434rkH';
const kClientId = '5r9dhp6nptf0inulgtr864ahg6';
const kAdminPoolId = 'us-east-1_siK2jdgRp';
const kAdminClientId = '441p8p6i8k6ge2a6mf5blj7124';
const kIdentityPoolId = 'us-east-1:93bb9e28-8aa5-4f4b-9c90-f23859ed9dfe';
const kRegion = 'us-east-1';
const kUserBucketName = 'phitnest-user-bucket-dev';
const kHost = 'https://65qubsxpzi.execute-api.us-east-1.amazonaws.com/prod/';
const kPort = '443';
