# Do not edit this file. It is automatically generated by CI/CD.
const kUserPoolId = us-east-1_tt6VzILxS;
const kClientId = 57oj9rjcimoe3umgcu8ddgejkc;
const kAdminPoolId = us-east-1_wgiGn2Eve;
const kAdminClientId = 5kicf5fj2gv4cq3cpdrvrvhki;
const kIdentityPoolId = us-east-1:68aac745-09d3-4210-bc4e-e145cf98f0c8;
const kRegion = us-east-1;
const kUserBucketName = phitnest-user-bucket-dev;
const kHost = https://tyu8jchjnl.execute-api.us-east-1.amazonaws.com/prod/;
const kPort = 443;
