// Do not edit this file. It is automatically generated by CI/CD.
const kUserPoolId = 'us-east-1_3lOk4Cjgt';
const kClientId = '6192nkjbcv68iq64flvmaacoh2';
const kAdminPoolId = 'us-east-1_jpc2asx6R';
const kAdminClientId = '16d2surc67h1hlro97gqa6kb2e';
const kIdentityPoolId = 'us-east-1:06fc57b0-a7c6-45d4-854b-1c173c7696e9';
const kRegion = 'us-east-1';
const kUserBucketName = 'phitnest-user-bucket-dev';
const kHost = 'https://5dxa51ydh0.execute-api.us-east-1.amazonaws.com/prod/';
const kPort = '443';
