AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PhitNest-API

#### GLOBALS ####
Globals:
  Function:
    Timeout: 25
    Environment:
      Variables:
        REGION: us-east-1
        COGNITO_USER_POOL_ID: !Ref UserCognitoUserPool
        COGNITO_USER_POOL_APP_ID: !Ref UserCognitoUserPoolClient

#### Input Parameters ####
Parameters:
  Stage:
    Type: String
    Description: Parameter for getting the deployment stage
    Default: default

#### Conditions ####
Conditions:
  CreateSandboxResources: !Equals [!Ref Stage, sandbox]

Resources:
  #### API GATEWAY ####
  PhitNestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors: '''*'''
      Name: !Sub "PhitNest-${Stage}-API"
      Auth:
        Authorizers:
          UserCognitoAuthorizer:
            UserPoolArn: !GetAtt UserCognitoUserPool.Arn
  
  #### COGNITO ####
  UserCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "PhitNest-${Stage}"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        From: "PhitNest <verify@phitnest.com>"
        ReplyToEmailAddress: "verify@phitnest.com"
        SourceArn: arn:aws:ses:us-east-1:235601651768:identity/phitnest.com
      AutoVerifiedAttributes:
      - email
      UsernameAttributes:
      - email
      - phone_number
      Schema:
      - AttributeDataType: String
        Name: email
        Required: true

  UserCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserCognitoUserPool
      EnableTokenRevocation: true
      ExplicitAuthFlows:
      - ALLOW_USER_SRP_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
      - ALLOW_CUSTOM_AUTH
      - ALLOW_USER_PASSWORD_AUTH
      ClientName: !Sub "PhitNest-${Stage}"
      GenerateSecret: false

  #### CODEGEN STARTS BELOW HERE ####
