
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PhitNest-API

#### GLOBALS ####
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        REGION: us-east-1
        COGNITO_USER_POOL_ID: !Ref CognitoUserPool
        COGNITO_USER_POOL_APP_ID: !Ref CognitoUserPoolClient

#### Input Parameters ####
Parameters:
  Stage:
    Type: String
    Description: Parameter for getting the deployment stage
    Default: default

#### Conditions ####
Conditions:
  CreateSandboxResources: !Equals [!Ref Stage, sandbox]

Resources:

  #### API GATEWAY ####
  PhitNestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors: '''*'''
      Name: !Sub "PhitNest-${Stage}-API"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
            Identity:
              Header: Authorization
              ValidationExpression: Bearer.*
  
  #### COGNITO ####
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "PhitNest-${Stage}"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      UsernameAttributes:
      - email
      - phone_number
      Schema:
      - AttributeDataType: String
        Name: email
        Required: true
      - AttributeDataType: String
        Name: family_name
        Required: true
      - AttributeDataType: String
        Name: given_name
        Required: true
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: !Sub "PhitNest-${Stage}"
      GenerateSecret: false

  #### CODEGEN STARTS BELOW HERE ####