name: CD aws

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      deployment_env:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: npm i -g aws-cdk pnpm turbo esbuild && pnpm install

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build
        run: turbo build --filter=(api|cognito)-*

      - name: Deploy
        id: deploy
        run: turbo deploy-${{ inputs.deployment_env }} --filter=aws*

      - name: Commit AWS development environment changes
        if: ${{ inputs.deployment_env == 'dev' }}
        uses: EndBug/add-and-commit@v9
        with:
          add: 'packages/dart-core/lib/config/aws.dart'
          author_name: The PhitMachine
          author_email: machine@phitnest.com
          commit: --signoff
          committer_name: The PhitMachine
          committer_email: machine@phitnest.com
          message: 'Saved CDK outputs'
          new_branch: master