name: CD Dev

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cd-aws:
    uses: ./.github/workflows/cd-aws.yaml
    with:
      deployment_env: dev
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  cd-ios:
    uses: ./.github/workflows/cd-ios.yaml
    secrets:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}