name: CD Dev

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cd:
    uses: ./.github/workflows/cd.yaml
    with:
      deployment_env: dev
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}