name: CD iOS

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MATCH_PASSWORD:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      APP_STORE_CONNECT_API_KEY_KEY:
        required: true

jobs:
  build_and_publish:
    runs-on: macos-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/ios/Gemfile
    steps:
      - name: Check out from git
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Setup ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: npm i -g aws-cdk pnpm turbo esbuild && pnpm install

      - name: Setup SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $MATCH_PASSWORD' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Install fastlane
        run: turbo build --filter=mobile

      - name: Build & Publish to TestFlight with Fastlane
        env:
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: turbo deploy --filter=mobile