name: CD Production

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cd-aws:
    uses: ./.github/workflows/cd-aws.yaml
    with:
      deployment_env: prod
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}