name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Permit execution of build tools
        run: chmod +x ./phitnest-api && chmod +x ./build_tools/template_gen.sh

      - name: Install dependencies
        run: ./phitnest-api install

      - name: Run prettier-eslint
        run: npm run lint

      - name: Create bind mount source directory for Dgraph
        run: mkdir -p ${{ github.workspace }}/dgraph-test/data

      - name: Run tests
        run: sudo ./phitnest-api test ${{ github.workspace }}/dgraph-test/data