name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Run prettier-eslint
        run: npm run lint

      - name: Permit execution of the codegen scripts
        run: chmod +x ./scripts/gen_combined_schema.sh && chmod +x ./scripts/template_gen.sh

      - name: Create bind mount source directory for Dgraph
        run: mkdir -p ${{ github.workspace }}/dgraph-test/data

      - name: Run tests
        run: make test DGRAPH_TEST_DIR=${{ github.workspace }}/dgraph-test/data