name: CI

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
          repository: PhitNest/phitnest
          ref: ${{ github.ref_name }} 
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Install dependencies
        run: npm i -g aws-cdk pnpm turbo && pnpm install

      - name: Run tests
        run: turbo test