name: Publish (iOS)

on:
  release:
    types: [published]
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: macos-latest

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/ios/Gemfile
      GH_ACCESS_PAT: ${{ secrets.GH_ACCESS_PAT }}

    steps:
      - name: Check out from git
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Setup ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Create .env
        run: mv .env.example.prod .env

      - name: Download dependencies
        run: flutter pub get

      - name: Setup SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $MATCH_PASSWORD' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null

      - name: Install fastlane
        run: bundle install --gemfile=$BUNDLE_GEMFILE

      - name: Build & Publish to TestFlight with Fastlane
        env:
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: cd ios && bundle exec fastlane ios beta "build_name:${{ github.ref_name }}"
